- README.md
> Include badge for CI #6

- src/webdriver/components/sidebar/extensions/ExtensionsViewSection.ts
- test/test-project/package.json
- test/test-project/src/test/xsideBar/xtensionsView-test.ts
fix #15 . Who would have guessed extensions would have spaces in their names...
> Find extensions with spaces in their title

- src/webdriver/components/sidebar/extensions/ExtensionsViewItem.ts
- src/webdriver/components/sidebar/extensions/ExtensionsViewSection.ts
- src/webdriver/locators/locators.ts
- src/webdriver/locators/versions/1.37.0.ts
- test/test-project/src/test/xsideBar/xtensionsView-test.ts
Changed way of looking for extensions.
Fixed #20.
> Fix extension searching algorithm

- src/util/codeUtil.ts
> Fix launch errors on path with spaces

- src/cli.ts
- src/extester.ts
- src/util/codeUtil.ts
> Fix run-tests command

- src/cli.ts
- src/extester.ts
- src/suite/runner.ts
- src/util/codeUtil.ts
- test/test-project/package.json
> Add -u flag to uninstall extension after test run

- src/webdriver/browser.ts
- src/webdriver/components/bottomBar/ProblemsView.ts
- src/webdriver/locators/locators.ts
- src/webdriver/locators/versions/1.37.0.ts
Currently fixes:
- Getting Started page opening with Code 1.38 and older
- ProblemsView marker lookup when labels include special characters
> Fixes for issue #33

- src/webdriver/components/bottomBar/AbstractViews.ts
- src/webdriver/components/bottomBar/Views.ts
- src/webdriver/components/editor/TextEditor.ts
- src/webdriver/components/workbench/input/Input.ts
- src/webdriver/native/openDialog.ts
- test/test-project/src/test/workbench/input-test.ts
> Fix various components getText methods

- src/util/unpack.ts
don't spam stdout to avoid #46
> Use quiet unzip to avoid stdout buffer error

- src/webdriver/browser.ts
- src/webdriver/components/workbench/input/Input.ts
> Fix quickpick selection on windows

- src/extester.ts
> Don't interpret windows paths as URL

- src/webdriver/browser.ts
- src/webdriver/components/editor/TextEditor.ts
There were some floating promises left in the code, I have simply added an await in front of them so that they are properly handled.
> await floating promises

- .travis.yml
> Add 1.43.0 and 1.44.0 in test matrix #92

- locators/lib/1.37.0.ts
- locators/lib/1.45.0.ts
- locators/package-lock.json
- locators/package.json
- native/package-lock.json
- page-objects/package-lock.json
- page-objects/package.json
- page-objects/src/components/editor/EditorView.ts
- page-objects/src/locators/locators.ts
- test/test-project/.mocharc.js
> vscode 1.45.x support

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/extester.ts
the main module is supposed to be available without the native handlers, but... I've made an error in the dependencies, so I need to break it all again
> Remove dependency on native module

- page-objects/src/components/editor/EditorView.ts
> Add proper synchronization to openEditor

- page-objects/src/components/editor/EditorView.ts
- page-objects/src/components/menu/ContextMenu.ts
- page-objects/src/components/menu/Menu.ts
- page-objects/src/components/menu/MenuItem.ts
- page-objects/src/components/sidebar/scm/ScmView.ts
This finishes the work started in 963d8749f233eb5600e0f970f70baa7f6fc2ba7f, see also #125
> Change all occurences of Promise<T|void> to Promise<T|undefined>

- page-objects/src/components/editor/SettingsEditor.ts
- test/test-project/package.json
- test/test-project/src/test/editor/settingsEditor-test.ts
fixes #155
Wasn't too sure how best to document this so lemme know if you want any changes making 🙂
> feat(settings): allow passing in multiple categories

- locators/lib/1.37.0.ts
- page-objects/src/components/workbench/input/Input.ts
- page-objects/src/locators/locators.ts
- test/test-project/package.json
- test/test-project/src/extension.ts
- test/test-project/src/test/workbench/input-test.ts
> Add select/deselect all quick picks

- page-objects/src/components/sidebar/extensions/ExtensionsViewItem.ts
> Wait for extension to install

- page-objects/src/components/menu/Menu.ts
> Wait enablement and display of menu item before selecting them

- src/suite/runner.ts
> Include error in console when screenshot capture failed #205

- .github/workflows/linux.yml
Given that latest is now 1.53.0
> Add 1.52.0 in test matrix #221

- src/util/codeUtil.ts
> Check for vsce instead of .bin folder

- .github/workflows/mac.yml
> Fix CI Mac workflow name

- api-handler/package-lock.json
- api-handler/src/workspace.ts
- locators/package-lock.json
- locators/package.json
- native/package-lock.json
- native/package.json
- package-lock.json
- package.json
- page-objects/package-lock.json
- test/test-project/package.json
> Remove native from build

- .github/workflows/insiders.yml
> provide Nightly build for Insider #94

- page-objects/src/components/editor/WebView.ts
> Await active-frame when switching to frame in WebView #301

- page-objects/src/components/sidebar/tree/custom/CustomTreeSection.ts
I was unable to test it locally but sharing to have feedback
> Await list of elements in Tree Section View #303

- page-objects/src/components/sidebar/tree/TreeSection.ts
- test/test-project/src/test/xsideBar/sideBarView-test.ts
> List other items when openItem errors out

- locators/lib/1.37.0.ts
- page-objects/src/components/sidebar/ViewItem.ts
- page-objects/src/components/sidebar/tree/custom/CustomTreeItem.ts
- page-objects/src/locators/locators.ts
- test/test-project/src/test/xsideBar/customView-test.ts
- test/test-project/src/treeView.ts
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> Add getDescription for CustomTreeItem(Fixes #312)

- package-lock.json
- package.json
This resolves runtime warning about outdated vsce.
> Bump vsce version

- src/util/codeUtil.ts
> Ensure outdated extensions are updated

- .github/workflows/linux.yml
- locators/package-lock.json
- package-lock.json
- package.json
- page-objects/package-lock.json
> Update version to 4.2.4 and include sec. fixes

- .github/workflows/insiders.yml
- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/windows.yml
- .gitignore
- locators/package-lock.json
- locators/package.json
- package.json
- page-objects/package-lock.json
- page-objects/package.json
- page-objects/src/components/bottomBar/Views.ts
- test/test-project/package.json
- test/test-project/src/test/debug/debug-test.ts
Propose switch to node.js 16
Extend .gitignore
> Update CI to include 1.65 vscode version

- package-lock.json
> Update package-lock after types/node updated to 16

- locators/package-lock.json
- locators/package.json
> Update page-object deps 2.0.0

- .github/workflows/linux.yml
- test/test-project/src/test/dialog/dialog-test.ts
- test/test-project/src/test/menu/contextMenu-test.ts
> Extend tested systems to 1.67.2 and latest - 1.68.x

- src/extester.ts
- src/suite/mochaHooks.ts
> #193 - Take screenshot when mocha hook fails

- .github/workflows/linux.yml
> Add 1.68.1 in tested matrix

- src/suite/runner.ts
> Increase timeout for mocha suite afterAll method

- CHANGELOG.md
- package-lock.json
- package.json
> Update monaco-page-objects dependency to 2.0.1

- .github/workflows/linux.yml
- src/cli.ts
- src/extester.ts
> Add placeholder min/max values to --code_version option, fixes #480

- .gitignore
- src/browser.ts
- src/cli.ts
- src/suite/runner.ts
- src/util/codeUtil.ts
- test/test-project/.vscode/settings.json
- test/test-project/package.json
- test/test-project/src/test/01_general/resource-test.ts
> Add open resource CLI/API option

- locators/lib/1.37.0.ts
- page-objects/src/components/editor/SettingsEditor.ts
- page-objects/src/components/sidebar/ViewItem.ts
- page-objects/src/components/workbench/Notification.ts
- page-objects/src/locators/locators.ts
- test/test-project/src/test/editor/settingsEditor-test.ts
- test/test-project/src/test/workbench/notifications-test.ts
> issue-493: Rewrite synchronized getters in some of the classes like Notifications, TitleBar, etc. to async

- src/extester.ts
> Bump max supported VSCode version to 1.71.2

- package-lock.json
> Bump vsce to 2.11.0 in package-lock.json

- .github/workflows/mac.yml
- .github/workflows/windows.yml
> Use max placeholder in Mac/Win GH actions matrix

- src/cli.ts
- src/extester.ts
> Apply min/max feature to API

- page-objects/src/components/workbench/DebugToolbar.ts
I tried to add tests but I struggle with creating them.
Resolves #511 
> Add Disconnect button click to DebugToolBar

- page-objects/src/components/sidebar/ViewItem.ts
- page-objects/src/components/sidebar/tree/default/DefaultTreeItem.ts
- page-objects/src/errors/NullAttributeError.ts
- page-objects/src/index.ts
This PR prohibits '' and null string cases mentioned in #482. Although it will not solve the whole problem.
> Add label check to ViewItem

- .github/workflows/linux.yml
- locators/lib/1.73.0.ts
- src/extester.ts
- src/util/codeUtil.ts
- test/test-project/src/test/bottomBar/views-test.ts
> Provide support for VSCode 1.73.x

- locators/lib/1.37.0.ts
- locators/lib/1.74.0.ts
- page-objects/src/components/editor/WebView.ts
- page-objects/src/locators/locators.ts
> Fix WebView component for vscode 1.74+

- src/suite/mochaHooks.ts
> Fix hook context

- .github/workflows/linux.yml
- page-objects/src/components/sidebar/tree/custom/CustomTreeSection.ts
- src/extester.ts
- src/util/codeUtil.ts
- test/test-project/src/test/xsideBar/customView-test.ts
> Provide support for VSCode 1.74.0

- .github/workflows/mac.yml
- page-objects/src/components/sidebar/tree/custom/CustomTreeSection.ts
- test/test-project/.gitignore
- test/test-project/.vscodeignore
- test/test-project/package.json
- test/test-project/src/test/xsideBar/customView-test.ts
> Flaky CustomTreeSection > getVisibleItems tests on macOS

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/windows.yml
> Renaming master to main in GA, fixes #459

- .github/dependabot.yml
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
> Configure dependabot to increase version in requirements

- package-lock.json
- package.json
Reverts redhat-developer/vscode-extension-tester#570
> Revert "Bump got from 11.8.6 to 12.5.3"

- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.74.3

- .github/workflows/insiders.yml
- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/windows.yml
This should speedup execution.
> Enable npm package caching

- package-lock.json
- package.json
> Solve warnings about used deprecated dependencies

- .github/workflows/main.yml
- test/test-project/package.json
> Fix upload artifact step of main workflow to work for all runners

- .github/workflows/insiders.yml
- test/test-project/package.json
> Improve Insiders CI workflow

- KNOWN_ISSUES.md
- README.md
> Improve project readme file

- src/suite/mochaHooks.ts
> Fix invalid artefact screenshot path in GH Actions

- locators/lib/1.37.0.ts
- page-objects/src/components/editor/Breakpoint.ts
- page-objects/src/components/editor/TextEditor.ts
- page-objects/src/index.ts
- page-objects/src/locators/locators.ts
- test/test-project/src/test/debug/debug-test.ts
> Add function to get paused breakpoint

- src/util/codeUtil.ts
> Provide log warning when used vscode version differs from 'latest' version

- .github/workflows/insiders.yml
- .github/workflows/main.yml
- page-objects/src/components/bottomBar/Views.ts
- src/extester.ts
- test/test-project/.vscode/settings.json
- test/test-project/package.json
- test/test-project/src/test/debug/debug-test.ts
- test/test-project/src/test/editor/editorView-test.ts
- test/test-project/src/test/editor/textEditor-test.ts
- test/test-project/src/test/menu/titleBar-test.ts
- test/test-project/src/test/statusBar/statusBar-test.ts
- test/test-project/src/test/workbench/input-test.ts
> Support for latest stable VSCode 1.75.x release

- page-objects/src/components/editor/EditorView.ts
- test/test-project/src/test/editor/editorView-test.ts
> Override WebElement.isSelected for EditorTab class

- .github/workflows/main.yml
- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.76.1

- .github/workflows/insiders.yml
- .github/workflows/main.yml
- page-objects/src/components/bottomBar/Views.ts
- page-objects/src/components/editor/ContentAssist.ts
- page-objects/src/components/editor/EditorView.ts
- page-objects/src/components/editor/TextEditor.ts
- page-objects/src/components/workbench/Workbench.ts
- test/test-project/package.json
- test/test-project/src/test/bottomBar/bottomBarPanel-test.ts
- test/test-project/src/test/bottomBar/problemsView-test.ts
- test/test-project/src/test/bottomBar/views-test.ts
- test/test-project/src/test/debug/debug-test.ts
- test/test-project/src/test/editor/editorView-test.ts
- test/test-project/src/test/editor/settingsEditor-test.ts
- test/test-project/src/test/editor/textEditor-test.ts
- test/test-project/src/test/menu/macTitleBar-test.ts
- test/test-project/src/test/workbench/workbench-test.ts
- test/test-project/src/test/xsideBar/scmView-test.ts
- test/test-project/vscode-settings.json
> Run all possible tests also on macOS

- .github/workflows/insiders.yml
- .github/workflows/main.yml
- package.json
> Simplify build step workflow

- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.76.2

- src/browser.ts
- test/test-project/package.json
- test/test-project/vscode-settings.json
> Provide terminal.copyOnSelection as default extester vscode settings

- src/extester.ts
- src/util/codeUtil.ts
> Use vsce API instead CLI

- src/suite/runner.ts
> Remove .js and file existence restriction

- page-objects/src/components/workbench/Workbench.ts
> Remove versionInfo.browser check in Workbench

- .github/workflows/main.yml
- src/extester.ts
> Provide support for VS Code 1.77.0

- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.77.3

- .github/workflows/main.yml
- page-objects/src/components/bottomBar/Views.ts
- test/test-project/package.json
- test/test-project/src/test/bottomBar/views-test.ts
> Fix regression Terminal View bug in VS Code 1.67.2

- .github/workflows/main.yml
- locators/lib/1.37.0.ts
- locators/lib/1.70.0.ts
- page-objects/src/components/editor/EditorView.ts
- page-objects/src/locators/locators.ts
- test/test-project/package.json
- test/test-project/src/test/editor/editorView-test.ts
> Fix EditorView.getAction() is not working with VS Code 1.70+

- .github/workflows/main.yml
- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.78.2

- .github/workflows/main.yml
- src/extester.ts
> Shrink supported VS Code versions to last three releases

- sample-projects/helloworld-sample/.gitignore
- sample-projects/helloworld-sample/README.md
- sample-projects/helloworld-sample/package-lock.json
- sample-projects/helloworld-sample/package.json
- sample-projects/helloworld-sample/settings.json
- sample-projects/helloworld-sample/src/ui-test/bottomBar-test.ts
- sample-projects/helloworld-sample/src/ui-test/textEditor-test.ts
- sample-projects/helloworld-sample/tsconfig.json
- sample-projects/helloworld-sample/tslint.json
> Fix helloworld-sample tests from sample-projects

- page-objects/src/components/editor/TextEditor.ts
- test/test-project/src/test/editor/textEditor-test.ts
> issue-795: TextEditor > typeTextAt() method is not properly working mainly on macOS

- package-lock.json
- page-objects/src/components/bottomBar/AbstractViews.ts
- page-objects/src/components/bottomBar/Views.ts
- page-objects/src/components/editor/TextEditor.ts
- page-objects/src/components/workbench/input/Input.ts
- test/test-project/package.json
- test/test-project/src/test/system/clipboard.test.ts
> issue-687: Verify clipboard is preserved during test run

- src/util/download.ts
> issue-751: Fix RequestError: getaddrinfo ENOTFOUND

- page-objects/src/components/bottomBar/BottomBarPanel.ts
- test/test-project/src/test/bottomBar/bottomBarPanel-test.ts
> issue-785: BottomBar open view method is not working properly

- page-objects/src/components/editor/Editor.ts
- test/test-project/src/test/activityBar/activityBar-test.ts
- test/test-project/src/test/bottomBar/views-test.ts
- test/test-project/src/test/dialog/dialog-test.ts
- test/test-project/src/test/editor/customEditor-test.ts
- test/test-project/src/test/editor/editorView-test.ts
- test/test-project/src/test/workbench/input-test.ts
- test/test-project/src/test/xsideBar/scmView-test.ts
- test/test-project/src/test/xsideBar/sideBarView-test.ts
- test/test-project/src/test/xsideBar/xtensionsView-test.ts
> Fix unstable sideBarView-test on macOS

- .github/workflows/stalebot.yml
> Add action for stale inactive issues/PRs

- page-objects/src/components/editor/EditorView.ts
> Avoid flakiness when trying to activate opened editor tab in EditorView

- page-objects/src/components/bottomBar/AbstractViews.ts
- page-objects/src/components/bottomBar/Views.ts
- page-objects/src/components/editor/TextEditor.ts
- page-objects/src/components/workbench/input/Input.ts
> issue-835: Fix could not paste from clipboard issue only on Windows

- locators/tsconfig.json
- package-lock.json
- page-objects/package.json
- page-objects/src/components/bottomBar/AbstractViews.ts
- page-objects/src/components/bottomBar/Views.ts
- page-objects/src/components/editor/TextEditor.ts
- page-objects/src/components/workbench/input/Input.ts
- page-objects/tsconfig.json
- test/test-project/package.json
- test/test-project/src/test/system/clipboard.test.ts
- test/test-project/tsconfig.json
- tsconfig.json
> Bump clipboardy to 3.0.0

- .github/workflows/main.yml
- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.79.0

- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.79.1

- src/util/download.ts
> issue-859: Fix lookup timeout when downloading VSCode

- .github/dependabot.yml
> Update dependabot.yml to remove duplicates

- src/suite/mochaHooks.ts
- src/suite/runner.ts
> Sanitize filenames in ScreenshotCallbackFunction

- .github/workflows/main.yml
- page-objects/src/components/editor/TextEditor.ts
- src/extester.ts
- test/test-project/src/test/debug/debug-test.ts
> Bump 'max' placeholder to latest vscode 1.80.2

- .github/workflows/main.yml
- src/extester.ts
- test/test-project/src/test/bottomBar/bottomBarPanel-test.ts
- test/test-project/src/test/editor/textEditor-test.ts
> Bump 'max' placeholder to latest vscode 1.81.0

- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.81.1

- src/suite/runner.ts
> Raise mocha afterAll timeout from 60s to 180s

- .github/workflows/main.yml
- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.82.1

- package-lock.json
- package.json
- src/browser.ts
> Bump selenium-webdriver to 4.12.0 and @types/selenium-webdriver to 4.1.16

- src/extester.ts
> Bump 'max' placeholder to latest vscode 1.82.2

- src/cli.ts
- src/extester.ts
- src/util/codeUtil.ts
> issue-726: Add support for installing dependencies in the extest install-vsix command

- .github/workflows/insiders.yml
- .github/workflows/main.yml
- page-objects/src/components/editor/SettingsEditor.ts
- src/extester.ts
- test/test-project/src/test/editor/settingsEditor-test.ts
> Bump 'max' placeholder to latest VS Code 1.83.0

- src/extester.ts
> Bump 'max' placeholder to latest VS Code 1.83.1

- src/extester.ts
- src/util/codeUtil.ts
> issue-976: Provide colours for warning messages in console log

- .github/workflows/main.yml
- KNOWN_ISSUES.md
- locators/lib/1.84.0.ts
- src/extester.ts
> Bump 'max' placeholder to latest VS Code 1.84.2

- locators/lib/1.37.0.ts
- page-objects/src/components/bottomBar/ProblemsView.ts
- page-objects/src/locators/locators.ts
- test/test-project/src/test/bottomBar/problemsView-test.ts
- wiki/ProblemsView.md
> issue-742: Clicks not being intercepted in SideBarView and BottomBarPannel

- test/test-project/src/test/debug/debug-test.ts
> issue-408: Failed when call debugView.getText(), only on macOS

- page-objects/src/components/workbench/Workbench.ts
- test/test-project/package.json
- test/test-project/src/extension.ts
- test/test-project/src/test/workbench/workbench-test.ts
> issue-920: Workbench().executeCommand executes always the first command from quickPicks

- .github/dependabot.yml
> Add reviewers team for Dependabot PRs

- test/test-project/package.json
> Bump dependencies in test/test-project

- .github/workflows/main.yml
- locators/lib/1.85.0.ts
- page-objects/src/components/workbench/NotificationsCenter.ts
- src/extester.ts
- test/test-project/src/test/workbench/workbench-test.ts
> Bump 'max' placeholder to latest VS Code 1.85.1

- src/extester.ts
- src/suite/runner.ts
- src/util/codeUtil.ts
> Fix indentation of warning/error messages in console logs

- locators/lib/1.37.0.ts
- locators/lib/1.70.0.ts
- locators/lib/1.85.0.ts
- page-objects/src/components/sidebar/ViewTitlePart.ts
- page-objects/src/locators/locators.ts
> Fix typo in ViewTitlePart actionConstructor

- README.md
> Fix logo scaling in readme file

- .github/workflows/main.yml
- README.md
- src/browser.ts
- src/extester.ts
- src/util/driverUtil.ts
> issue-1108: Support for VS Code 1.86.0

- test/test-project/package.json
Bump typescript from 5.3.2 to 5.3.3
Bump @typescript-eslint/eslint-plugin from 6.21.0 to 7.0.1 Bump @typescript-eslint/parser from 6.21.0 to 7.0.1
> Bump typescript and typescript-eslint packages in test/test-project

- README.md
- src/extester.ts
> Bump 'max' placeholder to latest VS Code 1.86.2

- package-lock.json
- package.json
- page-objects/src/locators/loader.ts
- sample-projects/helloworld-sample/src/ui-test/bottomBar-test.ts
- sample-projects/helloworld-sample/src/ui-test/extensionsView-test.ts
- sample-projects/helloworld-sample/tsconfig.json
- src/cli.ts
- src/suite/runner.ts
- src/util/download.ts
- src/util/unpack.ts
> fix: Get rid off 'require' when importing dependencies

- sample-projects/helloworld-sample/.eslintrc.json
- sample-projects/helloworld-sample/tsconfig.json
> fix(helloworld-sample): Reported ESLint config errors

- src/extester.ts
> fix: Improve NodeJS warning message for users

- src/extester.ts
- src/util/codeUtil.ts
> fix: 'ms-enable-electron-run-as-node' is not in the list of known options

- CHANGELOG.md
- package-lock.json
- package.json
> build(release): 7.2.0

- README.md
> chore: Add info about NodeJS support policy into readme

- CONTRIBUTING.md
> chore: Improve contribution guide

- sample-projects/helloworld-sample/.vscode/launch.json
> fix(sample-projects): Add missing --extensions_dir into helloworld-sample launch config

- .github/workflows/template-main.yaml
- .gitignore
- CONTRIBUTING.md
- locators/package.json
- package-lock.json
- package.json
- page-objects/package.json
> build: Simplify npm scripts of the root project

- .github/workflows/main.yml
- KNOWN_ISSUES.md
- README.md
- locators/lib/1.37.0.ts
- locators/lib/1.87.0.ts
- page-objects/src/components/bottomBar/AbstractViews.ts
- page-objects/src/components/bottomBar/Views.ts
- page-objects/src/components/dialog/ModalDialog.ts
- page-objects/src/components/editor/SettingsEditor.ts
- page-objects/src/components/sidebar/ViewTitlePart.ts
- page-objects/src/components/sidebar/debug/DebugView.ts
- page-objects/src/components/sidebar/scm/NewScmView.ts
- page-objects/src/components/sidebar/scm/ScmView.ts
- page-objects/src/components/sidebar/tree/debug/BreakpointSectionItem.ts
- page-objects/src/components/sidebar/tree/default/DefaultTreeItem.ts
- page-objects/src/components/workbench/Notification.ts
- page-objects/src/locators/locators.ts
- src/extester.ts
- test/test-project/src/test/bottomBar/views-test.ts
- test/test-project/src/test/debug/debug-test.ts
> build(vscode): Bump 'max' placeholder to use VS Code 1.87.0

- .github/dependabot.yml
> chore: Remove helloworld-sample from dependabot updates

- sample-projects/helloworld-sample/package-lock.json
- sample-projects/helloworld-sample/package.json
- test/test-project/package.json
> build(deps-dev): Bump devDependencies for test and example projects

- locators/package.json
- package-lock.json
- package.json
- page-objects/package.json
- sample-projects/helloworld-sample/package-lock.json
- sample-projects/helloworld-sample/package.json
- test/test-project/package.json
> build(deps-dev): Bump @types/node to from 18.x.x to 20.11.30

- locators/package.json
> build(deps-peer): Specify minimal monaco-page-objets peerDependency version for locators

- sample-projects/helloworld-sample/package-lock.json
- sample-projects/helloworld-sample/package.json
- sample-projects/helloworld-sample/src/ui-test/bottomBar-test.ts
> chore: Use ExTester 7.3.0 in sample-projects/helloworld-sample

- .github/workflows/insiders.yml
- .github/workflows/main.yml
- .github/workflows/nodejs.yml
- .github/workflows/publish-wiki.yml
- .github/workflows/stalebot.yml
- .github/workflows/template-main.yaml
> chore: Improve github actions workflows

- .github/workflows/main.yml
- .github/workflows/publish-wiki.yml
- .github/workflows/stalebot.yml
> chore: Fix broken Wiki and Stale gh actions

- CONTRIBUTING.md
- locators/package.json
- package-lock.json
- package.json
- page-objects/package.json
- page-objects/src/locators/loader.ts
- page-objects/src/locators/locators.ts
- test/test-project/package.json
also move from 'ts-essentials' to 'type-fest' which seems to be more often updated
> fix: Get back dependencies to repair broken package install

- locators/package.json
- package-lock.json
- package.json
- page-objects/package.json
> build(release): 7.3.1

- sample-projects/helloworld-sample/package-lock.json
- sample-projects/helloworld-sample/package.json
> build(deps-dev): bump dependencies in sample-projects/helloworld-sample

- CONTRIBUTING.md
> docs: Fix typo in contributing guide

- .github/workflows/publish-wiki.yml
> fix: Add custom path to the publish wiki workflow

- examples/helloworld-extester/package-lock.json
- examples/helloworld-extester/package.json
> chore(examples): Bump vscode-extension-tester from 7.3.2 to 8.0.2 in helloworld-extester

- package-lock.json
- tests/test-project/package.json
> build(deps-dev): declare eslint 8.57.0 only as root devDependency

- packages/extester/package.json
> build: bump max placeholder from 1.88.0 to 1.88.1

- packages/extester/src/suite/runner.ts
This PR for allowing Mocha's grep/invert options through environment variables `MOCHA_GREP` and `MOCHA_INVERT`.
Following examples show how it can be used:
```
MOCHA_GREP="ExtensionsView" npm run test
MOCHA_GREP="ExtensionsView" MOCHA_INVERT=true npm run test
```
- I did manually tested them. I thought it would be enough as the changes are simple enough.
> Support MOCHA_GREP/MOCHA_INVERT envvars

- package-lock.json
- package.json
bump @types/node 20.12.2 to 20.12.7
bump lerna from 6.4.1 to 8.1.2
bump type-fest from 4.14.0 to 4.15.0
> build(deps-dev): bump lerna, type-fest and @types/node

- .github/dependabot.yml
> build: Fix dependabot updates configuration to work properly in monorepo style

- packages/page-objects/src/components/editor/SettingsEditor.ts
- packages/page-objects/src/components/menu/TitleBar.ts
- tests/test-project/src/test/debug/debug.test.ts
> docs: Fix VS Code naming convention in comments

- lerna.json
- package-lock.json
- package.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
> chore(release): Publish 8.1.0

- examples/helloworld-extester/package-lock.json
- examples/helloworld-extester/package.json
- examples/helloworld-extester/src/ui-test/notifications.test.ts
- fix tests
- bump other devDependencies
> chore(examples): Bump ExTester version to 8.1.0

- .github/workflows/coverage.yml
- package.json
- tests/test-project/package.json
- tests/test-project/src/test/debug/debug.test.ts
> build: Adding code coverage reports pipeline

- .github/workflows/main.yml
- README.md
- packages/extester/package.json
- packages/page-objects/src/components/sidebar/tree/debug/VariableSectionItem.ts
- tests/test-project/src/test/debug/debug.test.ts
- tests/test-project/src/test/editor/settingsEditor.test.ts
bump 'max' placeholder from 1.88.1 to 1.89.0
> feat: Add support for VS Code 1.89.x

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.2.0
- @redhat-developer/locators@1.1.1
- @redhat-developer/page-objects@1.1.1
> chore(release): Publish v8.2.0

- packages/extester/package.json
> chore: bump vscode-max from 1.89.0 to 1.89.1

- tests/test-project/src/test/bottomBar/problemsView.test.ts
- tests/test-project/src/test/bottomBar/views.test.ts
> fix(tests): Improving stability of bottomBar tests. 

- tests/test-project/src/test/debug/debug.test.ts
> fix(tests): Improving stability of debug test.

- tests/test-project/src/test/webview/webviewView.test.ts
> fix(tests): Improving stability of webview tests.

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.3.0
- @redhat-developer/locators@1.1.2
- @redhat-developer/page-objects@1.1.2
> chore(release): Publish v8.3.0

- packages/extester/package.json
> feat: bump vscode-max version from 1.90.0 to 1.90.2

- examples/helloworld-extester/package-lock.json
- examples/helloworld-extester/package.json
- bump vscode-extension-tester from 8.1.0 to 8.3.0
> chore(examples): bump devDependencies in examples/helloworld-extester

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.3.1
- @redhat-developer/locators@1.1.3
- @redhat-developer/page-objects@1.1.3
> chore(release): Publish v8.3.1

- tests/test-project/package.json
> fix: Ensures that system clipboard test will be executed as last one of whole suite

- package-lock.json
- package.json
- packages/extester/package.json
- packages/page-objects/src/components/editor/TextEditor.ts
- packages/page-objects/src/components/editor/WebView.ts
- packages/page-objects/src/components/sidebar/ViewSection.ts
- packages/page-objects/src/components/sidebar/scm/ScmView.ts
- tests/test-project/src/extension.ts
- tests/test-project/src/test/webview/webView.test.ts
> build(deps): bump selenium-webdriver and @types/selenium-webdriver

- packages/locators/lib/1.37.0.ts
- packages/page-objects/src/components/ElementWithContextMenu.ts
- packages/page-objects/src/components/activityBar/ActionsControl.ts
- packages/page-objects/src/components/activityBar/ActivityBar.ts
- packages/page-objects/src/components/activityBar/ViewControl.ts
- packages/page-objects/src/components/bottomBar/AbstractViews.ts
- packages/page-objects/src/components/bottomBar/ProblemsView.ts
- packages/page-objects/src/components/bottomBar/Views.ts
- packages/page-objects/src/components/editor/Editor.ts
- packages/page-objects/src/components/editor/EditorAction.ts
- packages/page-objects/src/components/editor/EditorView.ts
- packages/page-objects/src/components/editor/TextEditor.ts
- packages/page-objects/src/components/sidebar/ViewItem.ts
- packages/page-objects/src/components/sidebar/ViewSection.ts
- packages/page-objects/src/components/sidebar/ViewTitlePart.ts
- packages/page-objects/src/components/sidebar/scm/NewScmView.ts
- packages/page-objects/src/components/sidebar/scm/ScmView.ts
- packages/page-objects/src/components/sidebar/tree/debug/SectionBreakpoint.ts
- packages/page-objects/src/components/workbench/Notification.ts
- packages/page-objects/src/locators/locators.ts
- tests/test-project/package.json
- tests/test-project/src/test/editor/editorView.test.ts
> feat: Support for editor action buttons with dropdown

- README.md
> fix: update vscode supported max version badge in readme file

- tests/test-project/src/test/bottomBar/views.test.ts
> test: Modify terminal view tests to work also with zsh

- packages/page-objects/src/components/editor/SettingsEditor.ts
> fix: findSetting of Settings Editor getting results in wrong order

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.4.0
- @redhat-developer/locators@1.2.0
- @redhat-developer/page-objects@1.2.0
> chore(release): Publish v8.4.0

- .github/workflows/main.yml
> ci: Bump middle version of Main CI from 1.89.1 to 1.90.2

- .github/workflows/coverage.yml
> ci: Use Node 20 for Coverage CI workflow

- package-lock.json
- packages/extester/package.json
- packages/extester/src/util/unpack.ts
> fix: migrate unpack from shell exec to unzipper library

- packages/page-objects/src/components/menu/TitleBar.ts
- packages/page-objects/src/components/menu/WindowControls.ts
- tests/test-project/src/test/menu/titleBar.test.ts
**Window Control is no more available in a DOM of Visual Studio Code**
> fix: deprecating WindowControls which is not working a few versions a lready

- docs/EditorView.md
> fix(wiki): fix url to know issues in EditorView wiki page

- packages/locators/lib/1.37.0.ts
- packages/page-objects/src/components/sidebar/debug/DebugView.ts
- packages/page-objects/src/components/sidebar/tree/debug/CallStackItem.ts
- packages/page-objects/src/components/sidebar/tree/debug/DebugCallStackSection.ts
- packages/page-objects/src/index.ts
- packages/page-objects/src/locators/locators.ts
- tests/test-project/src/test/debug/debug.test.ts
> feat: Add Call Stack Support

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.5.0
- @redhat-developer/locators@1.3.0
- @redhat-developer/page-objects@1.3.0
> chore(release): Publish v8.5.0

- packages/extester/src/util/driverUtil.ts
> refactor: simplify get chromedriver logic method

- packages/locators/lib/1.37.0.ts
- packages/page-objects/src/components/workbench/input/Input.ts
- packages/page-objects/src/locators/locators.ts
- tests/test-project/src/test/workbench/input.test.ts
> fix: getQuickPicks and isSelected does not work as expected

- packages/locators/lib/1.90.0.ts
- tests/test-project/src/extension.ts
- tests/test-project/src/test/webview/webView.test.ts
- tests/test-project/src/test/webview/webviewView.test.ts
> fix: webView findWebElement returning undefined

- packages/extester/package.json
> feat: bump vscode-max from 1.92.1 to 1.92.2

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.6.0
- @redhat-developer/locators@1.4.0
- @redhat-developer/page-objects@1.4.0
> chore(release): Publish v8.6.0

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.6.1
- @redhat-developer/locators@1.4.1
- @redhat-developer/page-objects@1.4.1
> chore(release): Publish v8.6.1

- package-lock.json
- package.json
- packages/page-objects/package.json
> fix: cannot find module type-fest

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.7.0
- @redhat-developer/locators@1.5.0
- @redhat-developer/page-objects@1.5.0
> chore(release): Publish v8.7.0

- README.md
> docs: update readme project file

- packages/extester/package.json
> feat: bump vscode-max from 1.93.0 to 1.93.1

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.8.0
- @redhat-developer/locators@1.6.0
- @redhat-developer/page-objects@1.6.0
> chore(release): Publish 8.8.0

- package-lock.json
- packages/extester/package.json
> build(deps): bump got from 13.0.0 to 14.4.3

- packages/extester/package.json
> feat: bump vscode-max from 1.94.0 to 1.94.2

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.8.1
- @redhat-developer/locators@1.6.1
- @redhat-developer/page-objects@1.6.1
> chore(release): Publish 8.8.1

- packages/extester/package.json
> feat: bump vscode-max from 1.95.0 to 1.95.1

- .github/workflows/coverage.yml
- .github/workflows/main.yml
- .github/workflows/template-main.yaml
> chore(ci): enable tests on ubuntu 24.04

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.8.2
- @redhat-developer/locators@1.6.2
- @redhat-developer/page-objects@1.6.2
> chore(release): Publish 8.8.2

- packages/extester/package.json
> feat: bump vscode-max from 1.95.1 to 1.95.2

- CONTRIBUTING.md
> docs: update contributing new release section post tasks

- packages/extester/package.json
> feat: bump vscode-max from 1.95.2 to 1.95.3

- README.md
- packages/extester/README.md
> docs: improve readme files of root and extester package

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.10.0
- @redhat-developer/locators@1.8.0
- @redhat-developer/page-objects@1.8.0
> chore(release): Publish 8.10.0

- tests/test-project/.vscodeignore
> chore: exclude test files from testing extension vsix pack

- packages/extester/src/extester.ts
> fix: install-vsix on windows using file patterns

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.11.0
- @redhat-developer/locators@1.9.0
- @redhat-developer/page-objects@1.9.0
> chore(release): Publish 8.11.0

- .github/workflows/template-main.yaml
> chore(ci): Switch pipeline back to ubuntu-latest

- docs/BottomBarPanel.md
- packages/page-objects/src/components/bottomBar/BottomBarPanel.ts
- tests/test-project/src/test/bottomBar/bottomBarPanel.test.ts
- tests/test-project/src/test/webview/webviewView.test.ts
> feat: BottomBarPanel support for custom tabs

- packages/extester/package.json
> feat: bump vscode-max from 1.96.2 to 1.96.3

- .github/dependabot.yml
> chore(ci): Group eslint for dependabot upgrades

- packages/extester/src/util/codeUtil.ts
> fix: use specified test directory for temporary folders

- packages/extester/package.json
> chore: bump vscode-max from 1.96.3 to 1.96.4

- .github/release.yml
> chore: improve release notes configuration

- package-lock.json
- package.json
- packages/extester/src/util/unpack.ts
> build(deps-dev): bump @types/targz from 1.0.4 to 1.0.5

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.12.0
- @redhat-developer/locators@1.10.0
- @redhat-developer/page-objects@1.10.0
> chore(release): Publish 8.12.0

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.13.0
- @redhat-developer/locators@1.11.0
- @redhat-developer/page-objects@1.11.0
> chore(release): Publish 8.13.0

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.14.0
- @redhat-developer/locators@1.12.0
- @redhat-developer/page-objects@1.12.0
> chore(release): Publish 8.14.0

- packages/extester/package.json
> chore: bump vscode-max from 1.99.1 to 1.99.2

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.14.1
- @redhat-developer/locators@1.12.1
- @redhat-developer/page-objects@1.12.1
> chore(release): Publish 8.14.1

- packages/extester/package.json
> chore: bump vscode-max from 1.99.2 to 1.99.3

- packages/extester/src/util/download.ts
Fixes: #1853
https://issues.redhat.com/browse/AAP-45167
> feat: make getFile retry downloads

- .github/dependabot.yml
- .prettierignore
- CODEOWNERS
> fix(dependabot): reviewers field in the dependabot.yml file will be removed soon

- packages/locators/lib/1.37.0.ts
- packages/page-objects/src/components/editor/ExtensionEditorDetailsSection.ts
- packages/page-objects/src/locators/locators.ts
- tests/test-project/src/test/editor/extensionEditor.test.ts
> feat: add support for readme in ExtensionEditorDetailsSection

- package.json
- packages/extester/src/util/codeUtil.ts
Related: https://github.com/microsoft/vscode/issues/204005
> chore: filter unsupported NODE_* variables when calling VS Code

- package-lock.json
> chore(deps): security patch for tar-fs

- packages/page-objects/src/components/workbench/input/Input.ts
- tests/test-project/src/test/workbench/input.test.ts
> fix: InputBox.selectQuickPick is not working properly for File/Folder picker

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.15.0
- @redhat-developer/locators@1.13.0
- @redhat-developer/page-objects@1.13.0
> chore(release): Publish 8.15.0

- packages/page-objects/src/components/editor/EditorView.ts
> feat: provide a timeout for EditorView.getAction

- package-lock.json
- packages/extester/package.json
- packages/locators/package.json
- packages/page-objects/package.json
- vscode-extension-tester@8.16.0
- @redhat-developer/locators@1.14.0
- @redhat-developer/page-objects@1.14.0
> chore(release): Publish 8.16.0

- packages/extester-runner/src/providers/screenshotsTreeProvider.ts
> feat(runner): support folders for screenshots

- packages/extester-runner/.vscodeignore
> chore(runner): do not include tests in extension vsix

- packages/extester/package.json
> chore: bump max VS Code version from 1.104.1 to 1.104.2
