redhat-developer/vscode-extension-tester

src/webdriver/native/openDialog.ts
should fix #13 since it no longer uses characters that would change keycodes between most layouts
@apupier would you care to try this out?
=> Use clipboard instead of typing text into dialogs

src/cli.ts, src/extester.ts, src/util/codeUtil.ts
This fixes #22.
Unfortunately, I don't really know how to test this, thus I'm not sure if it actually works…
=> Add option to pass the --yarn flag for the `vsce package` invocation

src/webdriver/components/workbench/Workbench.ts, src/webdriver/components/workbench/input/InputBox.ts, src/webdriver/components/workbench/input/QuickOpenBox.ts, test/test-project/src/test/bottomBar/problemsView-test.ts, test/test-project/src/test/editor/textEditor-test.ts, test/test-project/src/test/statusBar/statusBar-test.ts, test/test-project/src/test/workbench/input-test.ts, test/test-project/src/test/workbench/workbench-test.ts, test/test-project/src/test/xsideBar/sideBarView-test.ts
`create()` waits for the DOM to update and then constructs the page objects. Use as a way to safely wait for the input to appear.
=> Add create method to input objects

src/webdriver/components/workbench/input/Input.ts, src/webdriver/locators/locators.ts, src/webdriver/locators/versions/1.37.0.ts, test/test-project/package.json, test/test-project/src/extension.ts, test/test-project/src/test/workbench/input-test.ts
fix #59
getText will still be available but now will return all text contained in the element:
- getLabel will now return what getText used to
- getDescription will return the optional description of an item
=> Replace Quickpick#getText with getLabel and getDescription

src/cli.ts, src/extester.ts, src/util/codeUtil.ts, src/webdriver/browser.ts
This allows you to specify the path that will be used by VSCode to handle extensions.
Can be useful in order to launch your tests with an specific set of extensions. (e.g. copy the extensions that you want to use in your tests from your .vscode/extensions dir to a separate folder and use it in your tests).
Also can be used to prevent installed extensions to get in the way when running this project's tests (i got bitten by this issue).
Might be of help for this issue: https://github.com/redhat-developer/vscode-extension-tester/issues/33
=> Add support to specify VSCode extensions dir

page-objects/src/components/workbench/input/Input.ts
Currently `findQuickPick()` returns a `Promise<QuickPickItem|void>` which is inconvenient to use as you cannot use the return value directly without casting. For instance an assertion or the `?` operator only work on `null` or `undefined` but not on `void`.
This commit changes the return type to be consistent with the `Array.find()` function and returns now a `Promise<QuickPickItem|undefined>`, which removes the above inconveniences.
=> Make findQuickPick return undefined when no QuickPick is found

page-objects/src/index.ts
This allows us to directly use the type of the `openEditor` member function of the `EditorView` class.
=> Export the Editor class as well

page-objects/src/components/editor/TextEditor.ts
This member function retrieves the raw Uri of a text document. This can be used for Editor windows that show files not from the local file system but from some other Uri and for which `fileURLToPath()` fails.
=> Add getFileUri to TextEditor

README.md
The link was pointing to travis-ci.com, but the correct one is travis-ci.org
=> Fix Build Status badge URL

src/util/codeUtil.ts
The old url now redirects to https://update.code.visualstudio.com/api/releases/ which the download code does not follow, thereby unfortunately breaking vscode-extension-tester.
=> Correct apiUrl for downloading VSCode

src/browser.ts, src/cli.ts, src/extester.ts, src/suite/runner.ts, src/util/codeUtil.ts
Currently extester has a plethora of options, of which not all have to be set by
the user. This makes it awkward if one wants to use the default for most
options, but only modify the last one. To remedy this, we switch to objects for
all the optional arguments, which makes the API more convenient to use in this
case.
Note: this will probably warrant a major version bump.
=> Use destructured parameters

page-objects/src/components/workbench/Notification.ts, test/test-project/package.json, test/test-project/src/extension.ts, test/test-project/src/test/workbench/notifications-test.ts, test/test-project/src/treeView.ts
`indexOf()` returns a number which only evaluates to false if the result is 0, which is not correct, as the condition should evaluate to false when it is -1
=> Fix Notification.getType() not finding error notifications properly

locators/lib/1.37.0.ts, package-lock.json, package.json, page-objects/src/components/sidebar/ViewSection.ts, page-objects/src/components/sidebar/WelcomeContent.ts, page-objects/src/index.ts, page-objects/src/locators/locators.ts, test/test-project/package.json, test/test-project/src/extension.ts, test/test-project/src/test/xsideBar/customView-test.ts
This is a very crude and far from finished PR to add support for [Welcome Content](https://code.visualstudio.com/api/extension-guides/tree-view#welcome-content) in tree views.
To make things a bit complicated, every tree view section has a `welcome-view` and `welcome-view-content` sub element, but they are invisible/without content. When they are actually visible, then the content is present in the div with the class name `pane-body welcome`.
The part that is currently missing is which content to get out of the welcome view. Welcome views have afaik only text and buttons which can be clicked. The content is present as child element of the div with class name `welcome-view-content`. Text content is simply present in `<p>` elements, the buttons on the other hand use the `a` element with the …
=> Add API to access welcome content

page-objects/src/components/editor/TextEditor.ts, test/test-project/src/test/activityBar/viewControl-test.ts, test/test-project/src/test/editor/textEditor-test.ts
This function is rather convenient to be able to test that a command put us at the correct position.
=> Make TextEditor.getCoordinates() public 

page-objects/src/components/sidebar/ViewItem.ts, page-objects/src/components/sidebar/tree/custom/CustomTreeItem.ts, page-objects/src/components/sidebar/tree/default/DefaultTreeItem.ts, test/test-project/src/test/xsideBar/customView-test.ts, test/test-project/src/treeView.ts
- move `hasChildren` functionality to `isExpandable`
- rework `hasChildren` to actually count the child items
=> Change TreeItem children checks

src/browser.ts, src/suite/runner.ts, src/util/codeUtil.ts
The current logic for converting a `VSBrowserLogLevel` to `logging.Level` is broken because `logLevel` is actually a number and `toString()` does not result in the expected strings, but just in '0', '1', etc.
We use a dumb switch instead, which relies less on behavior that is not verifiable by the type checker.
=> Fix broken loglevel conversion

locators/lib/1.37.0.ts, page-objects/src/components/sidebar/ViewItem.ts, page-objects/src/components/sidebar/tree/TreeSection.ts, page-objects/src/locators/locators.ts, test/test-project/src/extension.ts, test/test-project/src/test/xsideBar/customView-test.ts, test/test-project/src/treeView.ts
Clicking on the tree item only works for tree items that have no command attached to them. For those that have a command bound to them, we have to use `expand()`, as we would otherwise only trigger the command but not expand it.
This PR also adds a regression test for such a case.
=> Dont click tree items to expand them, use expand instead

page-objects/src/components/statusBar/StatusBar.ts
When searching for a item in the StatusBar, skip items that encounter a `StaleElementReferenceError` instead of throwing an error.
Fixes https://github.com/redhat-developer/vscode-extension-tester/issues/346
=> Ignore stale items in StatusBar.getItem

locators/lib/1.37.0.ts, locators/lib/1.58.0.ts, test/test-project/src/test/statusBar/statusBar-test.ts
On versions of VSCode prior to 1.58 and when searching for a item in the StatusBar, use the element's aria-label attribute instead of its title attribute. This is because the aria-label is set to the visible text of the item, while the title is set to the tooltip. Not all items have a tooltip making those ones impossible to find.
Fixes https://github.com/redhat-developer/vscode-extension-tester/issues/345
=> Only use aria-label for Status Bar itemTitle

package-lock.json, package.json, src/util/download.ts
Hello
Here is a PR to fix #395, which is an issue with proxy settings.
Global Agent will allow to use HTTP(S)_PROXY and GLOBAL_AGENT_HTTP_PROXY env. var. for `got` request.
=> Use `Global Agent` to fix proxy / ca issues on `got` (Fix #395)

sample-projects/helloworld-sample/package.json
After "npm install" in the vscode-extension-tester/sample-projects/helloworld-sample folder, "npm run compile" gives multiple errors like:
error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try npm i --save-dev @types/jest or npm i --save-dev @types/mocha.
Adding "@types/mocha": "^9.0.0" to the "devDependencies" in package.json solves this issue.
=> Add missing @types/mocha dependency in helloworld example

page-objects/src/components/editor/EditorView.ts
Noticed that this was only closing the first group when a `groupIndex` was specified.
=> Close specified group

package-lock.json, package.json
As vsce version does not get updated magically, we need to upgrade
the minimum version in order to allow building projects with yarn.
Fixes #451
Related: https://github.com/microsoft/vscode-vsce/issues/742
=> Fix yarn compatibility

page-objects/src/components/bottomBar/Views.ts
This will unblock GH action "Insider" pipeline which was broken
last build with PR change passed - see [Nightly Insiders #540](https://github.com/redhat-developer/vscode-extension-tester/actions/runs/3122882801)
=> Stabilize TerminalView.getText() method for VSCode insider

package-lock.json, package.json
it avoids having a CVE in transitive dependencies
not upgrading to 12.x as it requires more work given API breakage. This could be done in another iteration.
fixes #507
=> Upgrade got dependency to 11.8.5 version

package-lock.json, package.json
This change should enable yarn to link either locators or page-object
as previously it would complain that these folders are not correctly
declared as workspaces inside parent package.json
=> Declare locators and page-objects as workspaces

.github/workflows/insiders.yml, .github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
This will reduce GHA load and provide faster build results as there
is zero value in running build of a PR revision that was already
outdated.
=> Cancel in-progress builds if a PR is updated

page-objects/src/components/editor/WebView.ts, test/test-project/src/extension.ts, test/test-project/src/test/editor/editorView-test.ts, test/test-project/src/test/editor/webView-test.ts
=> Cannot use WebView.switchToFrame() with VSCode 1.74+ when there are several webview opened

locators/lib/1.37.0.ts, page-objects/src/components/AbstractElement.ts, page-objects/src/locators/locators.ts
Currently, only Selenium enabled check is in place. However, the Selenium check does not verify whether an element is disabled by other means than standard way.
=> Add 'disabled' check for vscode components

locators/lib/1.76.0.ts, page-objects/src/components/editor/EditorAction.ts, page-objects/src/components/editor/EditorView.ts, page-objects/src/index.ts, test/test-project/src/test/editor/editorView-test.ts
Currently, one must call getAttribute to get Editor Action Button label which is not ideal. Also, by adding this feature it will be possible to use predicate that is more flexible than title matching.
=> Add EditorAction Page Object

page-objects/src/components/editor/TextEditor.ts, test/test-project/src/test/editor/textEditor-test.ts
=> Delegate Codelens actions directly to <a> element

page-objects/src/components/workbench/input/InputBox.ts
This lack in the API was a reason for flakiness in our tests, and I thought this would be appropriate as it is with other functions
closes https://github.com/redhat-developer/vscode-extension-tester/issues/821
=> Add timeout to InputBox's create function

page-objects/src/components/dialog/ModalDialog.ts, test/test-project/src/test/dialog/dialog-test.ts
=> Improve stability of Modal dialog tests

page-objects/src/components/editor/TextEditor.ts, test/test-project/src/codelensProvider.ts, test/test-project/src/test/editor/textEditor-test.ts
Hi, 
Changed logic:
1. getCodeLenses, xpath changed from `.//span[contains(@widgetid, 'codelens.widget')]` to `.//span[contains(@widgetid, 'codelens.widget')]/a[@id]` to select all codelenses and not codelenses container
2. CodeLens constructor changed from `super(element.findElement(By.css('a')), editor);` to `super(element, editor);`
So these changes should fix #902 reported bug 
Check for new xpath ->
---
~- **DO** make sure any public APIs changes are documented.~ No changes 
=> Fix getCodeLenses logic

page-objects/src/components/bottomBar/Views.ts
The main idea here is to avoid copy redundancy that can affect memory use on Linux.
Based on the fact that from version [5.5.2 ](https://github.com/redhat-developer/vscode-extension-tester/blob/faf62dc386582f2d045a52d4f724adc80c1855e1/CHANGELOG.md?plain=1#L66) terminal.copyOnSelection is default setting and there is no need for extra warning for macOS users and extra condition for Linux
Hope it will help to avoid issue https://github.com/redhat-developer/vscode-extension-tester/issues/918
---
~~- [ ] **CONSIDER** adding a new test if your PR resolves an issue.~~
~~- [ ] **DO** make sure any public APIs changes are documented.~~
=> issue-918: Delete copy operation redundancy

package-lock.json, package.json, page-objects/src/components/bottomBar/BottomBarPanel.ts, src/cli.ts, src/suite/runner.ts, test/test-project/src/test/bottomBar/views-test.ts, test/test-project/src/test/xsideBar/scmView-test.ts
=> Bump glob to 10.3.4

page-objects/src/components/editor/TextEditor.ts, test/test-project/src/test/debug/debug-test.ts
Just an idea to hold info about toggled breakpoints in the text editor object attribute 
Will be glad to read feedback and better ideas
fix #904 
---
=> Add multipple breakpoints to editor

.github/workflows/insiders.yml, .github/workflows/main.yml, .gitignore, src/browser.ts, src/extester.ts, src/util/codeUtil.ts, src/util/driverUtil.ts, wiki/Taking Screenshots.md, wiki/Test-Setup.md
=> issue-485: Avoid to get invalid socket file which causes webdriver unknown error

locators/lib/1.85.0.ts
Fix #605
See Screenshot for proof:
=> Update ActionConstructor for ViewTitlePart

src/util/codeUtil.ts, src/util/driverUtil.ts
Downloads:
- the universal binary of VSCode on MacOS
- the appropriate binary (intel or arm) of ChromiumDriver on MacOS.
Closes #1082 
This ensures that VSCode does not run in an emulation layer on MacOS ARM, which slows down the UI substantially on my machine (an M1 MacBook Air).
=> Download appropriate binaries on MacOS

.github/workflows/nodejs.yml, .github/workflows/template-main.yaml, README.md
=> build: Provide pipeline for testing with NodeJS 20.x and 21.x

src/util/codeUtil.ts
=> fix: Update codeUtil.ts to download vscode for linux-arm64

sample-projects/helloworld-sample/src/ui-test/textEditor-test.ts
=> fix(helloworld-sample): Stabilise textEditor tests in sample project

.vscode/settings.json, locators/tsconfig.json, page-objects/src/components/bottomBar/AbstractViews.ts, page-objects/tsconfig.json, test/test-project/.eslintignore, test/test-project/.eslintrc.js, test/test-project/tsconfig.json, tsconfig.json
=> fix: Improve TSconfig setup and fix errors in test/test-project

.github/workflows/template-main.yaml
=> fix(nodejs-build): Do not use unsupported special chars for artifacts name in NodeJS workflow

CONTRIBUTING.md
=> docs(release-guide): Add steps how to release a new version of ExTester

CONTRIBUTING.md, locators/package.json, package-lock.json, package.json, page-objects/package.json
=> build(release): 7.3.0

package-lock.json, packages/extester/package.json
This reverts 20eb715 (#1197)
@dependabot upgraded to got 14, but that [now requires node 20](https://github.com/sindresorhus/got/releases/tag/v14.0.0). ExTester has just moved to node18 (thanks for that), but as is explained in the readme, it's not ready for node20.
During install of the latest version of extester you would get this message:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'got@14.2.1',
npm WARN EBADENGINE   required: { node: '>=20' },
npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
npm WARN EBADENGINE }
```
So I thought to help out to make a PR with that dependency reverted, and maybe tell dependabot to not try to update this, the next time it comes around. …
=> Reverted dependabots update to got 14 since it requires node 20

docs/TextEditor.md, packages/page-objects/src/components/editor/TextEditor.ts, tests/test-project/resources/file-with-spaces.ts, tests/test-project/resources/file-with-tabs.ts, tests/test-project/src/test/editor/textEditor.test.ts
=> fix: moveCursor fails on file with tabs

packages/page-objects/src/components/editor/TextEditor.ts, tests/test-project/src/test/editor/textEditor.test.ts
=> Reduce sleep time between cursor move in TextEditor

packages/page-objects/src/components/editor/TextEditor.ts, tests/test-project/src/test/debug/debug.test.ts
=> feat: Add TextEditor.getBreakpoints(): Promise<Breakpoint[]>

packages/page-objects/src/components/editor/TextEditor.ts, tests/test-project/src/test/debug/debug.test.ts
=> feat: Add TextEditor.getBreakpoint(line: number): Promise<Breakpoint>

docs/ExtensionEditorDetailsSections.md, docs/ExtensionEditorView.md, packages/locators/lib/1.37.0.ts, packages/page-objects/src/components/editor/ExtensionEditorDetailsSection.ts, packages/page-objects/src/components/editor/ExtensionEditorView.ts, packages/page-objects/src/index.ts, packages/page-objects/src/locators/locators.ts, tests/test-project/src/test/editor/extensionEditor.test.ts
=> feat: Add support for Extension Editor View

packages/page-objects/src/components/workbench/DebugToolbar.ts
=> feat: change waitForBreakPoint timeout datatype

tests/test-project/src/test/debug/debug.test.ts
=> fix(test): failing Debug Session > TextEditor: getBreakpoints test

docs/Test-Setup.md, packages/extester/src/cli.ts, packages/extester/src/extester.ts, packages/extester/src/util/codeUtil.ts
This change allows to install pre-release version of the extensions to the test instance when available in the marketplace.
This enables testing of pre-release versions of extension you depend on and detect breaking changes early.
I created this issue: https://github.com/redhat-developer/vscode-extension-tester/issues/1583
=> feat(cli): This change allows to install pre-release version of the extensions to the test instance when available in the marketplace

docs/Home.md
The `VSBrowser` class doesn't have a static `opneResources()` method.
=> VSBrowser.openResources: adjust the example

KNOWN_ISSUES.md
=> chore: Mention limitations for Ubuntu 24.04 and openResources()

packages/extester/src/browser.ts, packages/page-objects/src/components/activityBar/ViewControl.ts, packages/page-objects/src/components/bottomBar/AbstractViews.ts, packages/page-objects/src/components/editor/SettingsEditor.ts, packages/page-objects/src/components/editor/TextEditor.ts, packages/page-objects/src/components/sidebar/debug/DebugView.ts, packages/page-objects/src/components/sidebar/scm/NewScmView.ts, packages/page-objects/src/components/sidebar/tree/debug/VariableSectionItem.ts, packages/page-objects/src/components/workbench/Notification.ts, packages/page-objects/src/components/workbench/Workbench.ts, tests/test-project/src/test/bottomBar/views.test.ts, tests/test-project/src/test/debug/debug.test.ts, tests/test-project/src/test/dialog/dialog.test.ts, tests/test-project/src/test/editor/diffEditor.test.ts, tests/test-project/src/test/editor/editorView.test.ts, tests/test-project/src/test/editor/extensionEditor.test.ts, tests/test-project/src/test/statusBar/statusBar.test.ts, tests/test-project/src/test/workbench/input.test.ts, tests/test-project/src/test/workbench/notifications.test.ts, tests/test-project/src/test/xsideBar/scmView.test.ts, tests/test-project/src/test/xsideBar/sideBarView.test.ts, tests/test-project/src/test/xsideBar/xtensionsView.test.ts
Seems this is a known issue a semantic string comparison is not going to work for all version strings. 
=> fix: address comparison for version string

docs/CustomTreeSection.md, packages/page-objects/src/components/sidebar/WelcomeContent.ts, tests/test-project/src/test/xsideBar/customView.test.ts
=> feat: Provide WelcomeContentSection.getButton

packages/extester/src/util/codeUtil.ts
fix downloading arm64 on windows.
- when I ran the tests locally, some failed, but that seems unrelated to this change as the tests wouldn't even start without this change. 
- The failing tests seemed to be due to a modal that didnt get closed
=> fix: Support arm64 on windows

.vscode/extensions.json, .vscode/settings.json
This fixes a problem with current contributors that use vscode would
produce changes that are not passing CI/CD pipelines due to prettier
and eslint config, even if they run `npm run test` locally before
creating the pull-request.
Example of problems:
- spaces being used for identation on typescript source files
- JSON files not being formatted with expected identation (lerna does
not lint `.vscode/settings.json` but prettied from CI does.
=> chore: reformat code when using vscode

docs/Test-Setup.md, packages/extester/src/util/download.ts
there are some self signed certs in the certification chain for this machine im on. could I introduce an env variable to disable the TLS rejection check.
=> feat: allow download to disable tls check env flag
